// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Page$ReactTemplate = require("./page.bs.js");
var Client$ReactTemplate = require("./client.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, Page$ReactTemplate.make(/* Some */["S9phSjAORuA"], /* array */[]))])), "index");

/*  Not a pure module */
