// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function s(prim) {
  return prim;
}

function $$default(value, option) {
  if (option) {
    return option[0];
  } else {
    return value;
  }
}

function getExn(message, option) {
  if (option) {
    return option[0];
  } else {
    throw [
          Caml_builtin_exceptions.failure,
          message
        ];
  }
}

exports.s = s;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.getExn = getExn;
/* No side effect */
